[package]
name = "generate-btc-transaction"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.71"
bitcoin = "0.30.0"
clap = { version = "4.3.5", features = ["derive"] }
hex = "0.4.3"

[dev-dependencies]
rstest = "0.17.0"
